##
## GLIB-1.2 cmake find module.
##


IF(NOT CMAKE_CROSSCOMPILING)

## SET(GLIB_NAME "glib")
## FIND_PATH(GLIB_INCLUDE_DIR NAMES glib.h PATHS ${GLIB_ROOT_DIR})
## FIND_PATH(GLIB_CONFIG_INCLUDE_DIR glibconfig.h PATHS ${GLIB_ROOT_DIR})
## FIND_LIBRARY(GLIB_LIBRARY ${GLIB_NAME} PATHS ${GLIB_ROOT_DIR}/.libs)
## NCLUDE_DIRECTORIES(${GLIB_INCLUDE_DIR} ${GLIB_CONFIG_INCLUDE_DIR})

## ELSE(CMAKE_CROSSCOMPILING)

SET(GLIB_NAME "glib-2.0")

FIND_PATH(GLIB_INCLUDE_DIR NAMES glib.h PATHS /usr/include/${GLIB_NAME} /usr/include /usr/include/glib /usr/local/include /usr/local/include/glib /usr/local/include/${GLIB_NAME})
FIND_PATH(GLIB_CONFIG_INCLUDE_DIR glibconfig.h PATHS /usr/lib/${GLIB_NAME} /usr/local/lib/${GLIB_NAME} /usr/lib/${GLIB_NAME}/include /usr/local/lib/${GLIB_NAME}/include)
FIND_LIBRARY(GLIB_LIBRARY ${GLIB_NAME} PATHS /usr/lib /usr/local/lib)
INCLUDE_DIRECTORIES(${GLIB_INCLUDE_DIR} ${GLIB_CONFIG_INCLUDE_DIR} ${GLIB_INCLUDE_DIR}/glib)



IF (GLIB_INCLUDE_DIR AND GLIB_LIBRARY AND GLIB_CONFIG_INCLUDE_DIR)
	SET(GLIB_FOUND TRUE)
ENDIF (GLIB_INCLUDE_DIR AND GLIB_LIBRARY AND GLIB_CONFIG_INCLUDE_DIR)

IF (NOT GLIB_FOUND)
	IF (GLIB_FIND_REQUIRED)
		MESSAGE (FATAL_ERROR "${GLIB_NAME} development package is mandatory ! Please install from your distro media or download from ftp://ftp.gnu.org.")
	ENDIF (GLIB_FIND_REQUIRED)
ENDIF (NOT GLIB_FOUND)

ENDIF(NOT CMAKE_CROSSCOMPILING)
