##
## SPEEX cmake find module.
##
SET(PORTAUDIO_NAME "portaudio")

FIND_PATH(PORTAUDIO_INCLUDE_DIR NAMES portaudio.h PATHS /usr/include /usr/local/include)
FIND_LIBRARY(PORTAUDIO_LIBRARY ${PORTAUDIO_NAME} PATHS /usr/lib /usr/local/lib)
INCLUDE_DIRECTORIES(${PORTAUDIO_INCLUDE_DIR} ${PORTAUDIO_INCLUDE_DIR}/glib)


IF (PORTAUDIO_INCLUDE_DIR AND PORTAUDIO_LIBRARY)
	SET(PORTAUDIO_FOUND TRUE)
ENDIF (PORTAUDIO_INCLUDE_DIR AND PORTAUDIO_LIBRARY)

IF (NOT PORTAUDIO_FOUND)
	IF (PORTAUDIO_FIND_REQUIRED)
		MESSAGE (FATAL_ERROR "${PORTAUDIO_NAME} development package is mandatory ! Please install from your distro media or download from ftp://ftp.gnu.org.")
	ENDIF (PORTAUDIO_FIND_REQUIRED)
ENDIF (NOT PORTAUDIO_FOUND)

