##
## PTHREAD cmake find module.
##
IF(NOT CMAKE_CROSSCOMPILING)

SET(PTHREAD_NAME "pthread")

FIND_PATH(PTHREAD_INCLUDE_DIR NAMES pthread.h PATHS /usr/include /usr/local/include)
FIND_LIBRARY(PTHREAD_LIBRARY ${PTHREAD_NAME} PATHS /usr/lib /usr/local/lib)
INCLUDE_DIRECTORIES(${PTHREAD_INCLUDE_DIR} ${PTHREAD_INCLUDE_DIR}/glib)


IF (PTHREAD_INCLUDE_DIR AND PTHREAD_LIBRARY)
	SET(PTHREAD_FOUND TRUE)
ENDIF (PTHREAD_INCLUDE_DIR AND PTHREAD_LIBRARY)

IF (NOT PTHREAD_FOUND)
	IF (PTHREAD_FIND_REQUIRED)
		MESSAGE (FATAL_ERROR "${PTHREAD_NAME} development package is mandatory ! Please install from your distro media or download from ftp://ftp.gnu.org.")
	ENDIF (PTHREAD_FIND_REQUIRED)
ENDIF (NOT PTHREAD_FOUND)

ENDIF(NOT CMAKE_CROSSCOMPILING)
